import { Merchant, Product } from '@/types/catalog';

export const DEMO_MERCHANT: Merchant = {
  id: 'merchant_aquamart',
  name: 'NovaBazaar',
  description: 'A curated general-purpose online shopping merchant platform.',
  currency: 'INR',
  active: true,
};

export const SEED_PRODUCTS: Product[] = [
  // --- 1. ELECTRONICS (6) ---
  {
    id: 'elec_001',
    merchantId: 'merchant_aquamart',
    name: 'Nexa USB-C 7-in-1 Aluminum Hub',
    category: 'electronics',
    description: 'Multi-port USB-C hub with 4K HDMI, 100W PD charging, 3 USB 3.0 ports, and SD/TF card readers in durable Space Grey aluminum.',
    pricePaise: 249900, // ₹2,499
    currency: 'INR',
    attributes: {
      ports: '7-in-1',
      material: 'aluminum',
      color: 'Space Grey',
      warrantyMonths: 12,
    },
    stock: 25,
    deliveryInfo: { estimatedDays: 2, shippingFeePaise: 5000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/electronics/usb-c-hub.png',
  },
  {
    id: 'elec_002',
    merchantId: 'merchant_aquamart',
    name: 'SwiftLink Wireless Ergonomic Mouse',
    category: 'electronics',
    description: 'Silent 2.4GHz wireless mouse with adjustable DPI (800/1200/1600), ergonomic thumb rest, and long 18-month battery life.',
    pricePaise: 69900, // ₹699
    currency: 'INR',
    attributes: {
      connectivity: '2.4GHz Wireless',
      wireless: true,
      dpi: '1600',
      color: 'Matte Black',
    },
    stock: 42,
    deliveryInfo: { estimatedDays: 3, shippingFeePaise: 4000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/electronics/wireless-mouse.png',
  },
  {
    id: 'elec_003',
    merchantId: 'merchant_aquamart',
    name: 'KeyPro Compact Mechanical Keyboard',
    category: 'electronics',
    description: '75% layout RGB backlit mechanical keyboard with tactile brown switches, hot-swappable PCB, and USB-C detachable cable.',
    pricePaise: 349900, // ₹3,499
    currency: 'INR',
    attributes: {
      switchType: 'Tactile Brown',
      layout: '75%',
      backlight: 'RGB',
      color: 'Charcoal',
    },
    stock: 12,
    deliveryInfo: { estimatedDays: 2, shippingFeePaise: 6000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/electronics/mechanical-keyboard.png',
  },
  {
    id: 'elec_004',
    merchantId: 'merchant_aquamart',
    name: 'ClarityView 1080p Full HD Webcam',
    category: 'electronics',
    description: 'Pro 1080p 60fps webcam with dual noise-canceling microphones, privacy shutter, and auto light correction clip.',
    pricePaise: 229900, // ₹2,299
    currency: 'INR',
    attributes: {
      resolution: '1080p 60fps',
      microphone: 'Dual Noise-Canceling',
      color: 'Black',
    },
    stock: 18,
    deliveryInfo: { estimatedDays: 3, shippingFeePaise: 5000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/electronics/webcam.png',
  },
  {
    id: 'elec_005',
    merchantId: 'merchant_aquamart',
    name: 'SoundPulse Portable SSD 1TB',
    category: 'electronics',
    description: 'Ultra-fast USB 3.2 Gen 2 portable SSD with up to 1050MB/s read speed, drop-resistant rubberized shell.',
    pricePaise: 599900, // ₹5,999
    currency: 'INR',
    attributes: {
      capacity: '1TB',
      speed: '1050MB/s',
      color: 'Midnight Blue',
    },
    stock: 0, // OUT OF STOCK TEST ITEM
    deliveryInfo: { estimatedDays: 4, shippingFeePaise: 5000, freeShippingThresholdPaise: 100000, expressAvailable: false },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/electronics/portable-ssd.png',
  },
  {
    id: 'elec_006',
    merchantId: 'merchant_aquamart',
    name: 'VoltCharge 65W GaN Fast Charger',
    category: 'electronics',
    description: 'Compact 3-port 65W GaN wall charger with dual USB-C PD ports and USB-A port for laptops, tablets, and phones.',
    pricePaise: 189900, // ₹1,899
    currency: 'INR',
    attributes: {
      powerWatt: 65,
      ports: '2x USB-C + 1x USB-A',
      color: 'White',
    },
    stock: 30,
    deliveryInfo: { estimatedDays: 2, shippingFeePaise: 4000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/electronics/gan-charger.png',
  },

  // --- 2. MOBILE ACCESSORIES (5) ---
  {
    id: 'mobile_001',
    merchantId: 'merchant_aquamart',
    name: 'VoltFast 20W USB-C Power Adapter',
    category: 'mobile',
    description: '20W Power Delivery USB-C wall adapter engineered for high-speed charging of flagship smartphones and accessories.',
    pricePaise: 89900, // ₹899
    currency: 'INR',
    attributes: {
      wattage: '20W',
      connector: 'USB-C',
      color: 'White',
    },
    stock: 35,
    deliveryInfo: { estimatedDays: 2, shippingFeePaise: 3000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/mobile/20w-adapter.png',
  },
  {
    id: 'mobile_002',
    merchantId: 'merchant_aquamart',
    name: 'PowerCore 10000mAh Compact Power Bank',
    category: 'mobile',
    description: 'Sleek 10000mAh power bank featuring 22.5W fast output, dual USB-A and USB-C input/output ports, and LED display.',
    pricePaise: 129900, // ₹1,299
    currency: 'INR',
    attributes: {
      capacity: '10000mAh',
      wattage: '22.5W',
      color: 'Black',
    },
    stock: 28,
    deliveryInfo: { estimatedDays: 3, shippingFeePaise: 4000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/mobile/power-bank.png',
  },
  {
    id: 'mobile_003',
    merchantId: 'merchant_aquamart',
    name: 'FlexiView Magnetic Phone Stand',
    category: 'mobile',
    description: 'Fully adjustable aluminum desk phone stand with 360-degree rotation, non-slip silicone pads, and foldable travel design.',
    pricePaise: 49900, // ₹499
    currency: 'INR',
    attributes: {
      material: 'aluminum',
      color: 'Silver',
      foldable: true,
    },
    stock: 50,
    deliveryInfo: { estimatedDays: 2, shippingFeePaise: 3000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/mobile/phone-stand.png',
  },
  {
    id: 'mobile_004',
    merchantId: 'merchant_aquamart',
    name: 'DuraCable Braided USB-C Cable 2m',
    category: 'mobile',
    description: 'Heavy-duty 2-meter nylon braided USB-C to USB-C cable supporting 60W power delivery and 480Mbps data sync.',
    pricePaise: 39900, // ₹399
    currency: 'INR',
    attributes: {
      length: '2m',
      connector: 'USB-C to USB-C',
      material: 'nylon_braided',
      color: 'Dark Grey',
    },
    stock: 65,
    deliveryInfo: { estimatedDays: 3, shippingFeePaise: 3000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/mobile/usbc-cable.png',
  },
  {
    id: 'mobile_005',
    merchantId: 'merchant_aquamart',
    name: 'ShieldPro Tempered Glass Screen Protector 2-Pack',
    category: 'mobile',
    description: '9H hardness ultra-clear tempered glass screen protector pack with installation frame and oleophobic anti-fingerprint coating.',
    pricePaise: 29900, // ₹299
    currency: 'INR',
    attributes: {
      hardness: '9H',
      packSize: '2-Pack',
      color: 'Transparent',
    },
    stock: 75,
    deliveryInfo: { estimatedDays: 2, shippingFeePaise: 2500, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/mobile/screen-protector.png',
  },

  // --- 3. AUDIO (5) ---
  {
    id: 'audio_001',
    merchantId: 'merchant_aquamart',
    name: 'StudioPro Over-Ear Wireless Headphones',
    category: 'audio',
    description: 'Active Noise Canceling (ANC) Bluetooth 5.3 over-ear headphones with 40mm custom drivers, 30h battery life, and plush memory foam cushions.',
    pricePaise: 499900, // ₹4,999
    currency: 'INR',
    attributes: {
      wireless: true,
      batteryLife: '30h',
      noiseCancellation: true,
      color: 'Matte Black',
    },
    stock: 14,
    deliveryInfo: { estimatedDays: 2, shippingFeePaise: 6000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/audio/overear-headphones.png',
  },
  {
    id: 'audio_002',
    merchantId: 'merchant_aquamart',
    name: 'AirBeats Wireless Earbuds',
    category: 'audio',
    description: 'TWS wireless earbuds with quad mic environmental noise cancellation, IPX5 water resistance, low-latency gaming mode, and 24h total playback.',
    pricePaise: 179900, // ₹1,799
    currency: 'INR',
    attributes: {
      wireless: true,
      batteryLife: '24h',
      waterResistant: true,
      color: 'White',
    },
    stock: 31,
    deliveryInfo: { estimatedDays: 2, shippingFeePaise: 4000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/audio/wireless-earbuds.png',
  },
  {
    id: 'audio_003',
    merchantId: 'merchant_aquamart',
    name: 'SportBand Bluetooth Neckband',
    category: 'audio',
    description: 'Ergonomic magnetic neckband earphones with 10mm bass boost drivers, 16-hour playtime, and fast charging capability.',
    pricePaise: 99900, // ₹999
    currency: 'INR',
    attributes: {
      wireless: true,
      batteryLife: '16h',
      color: 'Navy Blue',
    },
    stock: 22,
    deliveryInfo: { estimatedDays: 3, shippingFeePaise: 4000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/audio/bluetooth-neckband.png',
  },
  {
    id: 'audio_004',
    merchantId: 'merchant_aquamart',
    name: 'PureTone USB-C Wired Earphones',
    category: 'audio',
    description: 'Digital Type-C in-ear earphones with built-in DAC chip, inline remote control, clear HD microphone, and tangle-free cable.',
    pricePaise: 39900, // ₹399
    currency: 'INR',
    attributes: {
      wireless: false,
      connector: 'USB-C',
      microphone: true,
      color: 'Black',
    },
    stock: 47,
    deliveryInfo: { estimatedDays: 2, shippingFeePaise: 3000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/audio/wired-earphones.png',
  },
  {
    id: 'audio_005',
    merchantId: 'merchant_aquamart',
    name: 'NanoBeat Mini Bluetooth Speaker',
    category: 'audio',
    description: 'Compact 5W portable speaker with 360-degree sound, 8-hour battery, built-in carabiner clip, and IPX7 waterproof rating.',
    pricePaise: 119900, // ₹1,199
    currency: 'INR',
    attributes: {
      wireless: true,
      batteryLife: '8h',
      powerWatt: 5,
      color: 'Forest Green',
    },
    stock: 0, // OUT OF STOCK TEST ITEM
    deliveryInfo: { estimatedDays: 3, shippingFeePaise: 4000, freeShippingThresholdPaise: 100000, expressAvailable: false },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/audio/bluetooth-speaker.png',
  },

  // --- 4. FITNESS (6) ---
  // Canonical Match fit_001 preserved
  {
    id: 'fit_001',
    merchantId: 'merchant_aquamart',
    name: 'ProGrip Non-Slip Yoga Mat 6mm',
    category: 'fitness',
    description: 'High-density eco TPE yoga mat with alignment lines and shoulder carrying strap. Non-slip texture on both sides for superior grip.',
    pricePaise: 129900, // ₹1,299
    currency: 'INR',
    attributes: {
      thickness: '6mm',
      material: 'TPE',
      color: 'Teal',
      nonSlip: true,
    },
    stock: 18,
    deliveryInfo: { estimatedDays: 3, shippingFeePaise: 6000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days returns.',
    active: true,
    imageUrl: '/products/fitness/yoga-mat.png',
  },
  {
    id: 'fit_002',
    merchantId: 'merchant_aquamart',
    name: 'FlexCore Resistance Band Set',
    category: 'fitness',
    description: '5-level heavy-duty natural latex resistance loop bands set with door anchor, handles, ankle straps, and travel carrying pouch.',
    pricePaise: 69900, // ₹699
    currency: 'INR',
    attributes: {
      material: 'natural_latex',
      pieceCount: 5,
      color: 'Multicolor',
    },
    stock: 40,
    deliveryInfo: { estimatedDays: 2, shippingFeePaise: 4000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/fitness/resistance-bands.png',
  },
  {
    id: 'fit_003',
    merchantId: 'merchant_aquamart',
    name: 'IronMax Dumbbell Pair 10kg',
    category: 'fitness',
    description: 'Pair of 5kg vinyl coated hex dumbbells with non-slip grip handles and anti-roll design for home gym strength training.',
    pricePaise: 349900, // ₹3,499
    currency: 'INR',
    attributes: {
      weightKg: 10,
      material: 'vinyl_cast_iron',
      color: 'Black',
    },
    stock: 8,
    deliveryInfo: { estimatedDays: 4, shippingFeePaise: 12000, freeShippingThresholdPaise: 100000, expressAvailable: false },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/fitness/dumbbell-pair.png',
  },
  {
    id: 'fit_004',
    merchantId: 'merchant_aquamart',
    name: 'SpeedPro Adjustable Skipping Rope',
    category: 'fitness',
    description: 'High-speed aluminum alloy handle jump rope with 360-degree dual ball bearings and tangle-free steel wire cable.',
    pricePaise: 39900, // ₹399
    currency: 'INR',
    attributes: {
      material: 'steel_wire',
      color: 'Silver',
    },
    stock: 55,
    deliveryInfo: { estimatedDays: 2, shippingFeePaise: 3000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/fitness/skipping-rope.png',
  },
  {
    id: 'fit_005',
    merchantId: 'merchant_aquamart',
    name: 'ActiveGo Gym Shaker Bottle 700ml',
    category: 'fitness', // preserved category fit_005
    description: 'BPA-free 700ml shaker bottle with stainless steel wire whisk ball, leakproof flip cap, and volume markings.',
    pricePaise: 49900, // ₹499
    currency: 'INR',
    attributes: {
      capacity: '700ml',
      material: 'tritan_plastic',
      color: 'Clear Smoke',
    },
    stock: 45,
    deliveryInfo: { estimatedDays: 2, shippingFeePaise: 3500, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/fitness/shaker-bottle.png',
  },
  {
    id: 'fit_006',
    merchantId: 'merchant_aquamart',
    name: 'RecoveryPro Deep Tissue Foam Roller',
    category: 'fitness',
    description: 'High-density EVA foam roller with grid trigger point texture for muscle recovery, physical therapy, and deep tissue massage.',
    pricePaise: 89900, // ₹899
    currency: 'INR',
    attributes: {
      material: 'EVA_foam',
      color: 'Deep Blue',
    },
    stock: 20,
    deliveryInfo: { estimatedDays: 3, shippingFeePaise: 5000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/fitness/foam-roller.png',
  },

  // --- 5. HOME & KITCHEN (6) ---
  {
    id: 'home_001',
    merchantId: 'merchant_aquamart',
    name: 'AquaBoil Electric Kettle 1.5L',
    category: 'home',
    description: 'Fast-boiling 1500W 1.5L double-wall stainless steel electric kettle with automatic shut-off and boil-dry protection.',
    pricePaise: 149900, // ₹1,499
    currency: 'INR',
    attributes: {
      capacity: '1.5L',
      powerWatt: 1500,
      material: 'stainless_steel',
      color: 'Silver',
    },
    stock: 24,
    deliveryInfo: { estimatedDays: 3, shippingFeePaise: 5000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/home/electric-kettle.png',
  },
  {
    id: 'home_002',
    merchantId: 'merchant_aquamart',
    name: 'MealFresh Stainless Steel Lunch Box',
    category: 'home',
    description: '3-tier leakproof stainless steel bento lunch box with silicone seal rings and insulated outer carrying tote bag.',
    pricePaise: 89900, // ₹899
    currency: 'INR',
    attributes: {
      capacity: '1.2L',
      material: 'stainless_steel',
      color: 'Grey',
    },
    stock: 33,
    deliveryInfo: { estimatedDays: 2, shippingFeePaise: 4000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/home/lunch-box.png',
  },
  {
    id: 'home_003',
    merchantId: 'merchant_aquamart',
    name: 'Precision Digital Kitchen Scale',
    category: 'home',
    description: 'High-precision digital food scale with 1g accuracy, tare function, backlit LCD display, and stainless steel platform.',
    pricePaise: 69900, // ₹699
    currency: 'INR',
    attributes: {
      capacity: '5kg',
      accuracy: '1g',
      color: 'Silver',
    },
    stock: 29,
    deliveryInfo: { estimatedDays: 2, shippingFeePaise: 3500, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/home/kitchen-scale.png',
  },
  {
    id: 'home_004',
    merchantId: 'merchant_aquamart',
    name: 'LockTight Food Storage Container Set',
    category: 'home',
    description: '4-piece borosilicate glass food storage container set with airtight locking lids. Microwave, oven, and dishwasher safe.',
    pricePaise: 119900, // ₹1,199
    currency: 'INR',
    attributes: {
      pieceCount: 4,
      material: 'borosilicate_glass',
      color: 'Clear',
    },
    stock: 19,
    deliveryInfo: { estimatedDays: 3, shippingFeePaise: 6000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/home/container-set.png',
  },
  {
    id: 'home_005',
    merchantId: 'merchant_aquamart',
    name: 'NeatSpace Ceramic Coffee Mug 400ml',
    category: 'home',
    description: 'Matte ceramic coffee mug with ergonomic handle and wooden coaster lid. 400ml capacity for coffee and tea.',
    pricePaise: 39900, // ₹399
    currency: 'INR',
    attributes: {
      capacity: '400ml',
      material: 'ceramic',
      color: 'White',
    },
    stock: 0, // OUT OF STOCK TEST ITEM
    deliveryInfo: { estimatedDays: 2, shippingFeePaise: 3000, freeShippingThresholdPaise: 100000, expressAvailable: false },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/home/coffee-mug.png',
  },
  {
    id: 'home_006',
    merchantId: 'merchant_aquamart',
    name: 'BreezeAir Compact USB Desk Fan',
    category: 'home',
    description: 'Quiet 3-speed USB powered personal desk fan with 360-degree tilt head and low acoustic noise output.',
    pricePaise: 99900, // ₹999
    currency: 'INR',
    attributes: {
      powerSource: 'USB',
      speeds: 3,
      color: 'Navy Blue',
    },
    stock: 16,
    deliveryInfo: { estimatedDays: 2, shippingFeePaise: 4000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/home/desk-fan.png',
  },

  // --- 6. FASHION (5) ---
  {
    id: 'fashion_001',
    merchantId: 'merchant_aquamart',
    name: 'CloudCotton Casual T-Shirt',
    category: 'fashion',
    description: '100% combed organic cotton heavyweight casual T-shirt. Relaxed fit with reinforced collar and breathable fabric.',
    pricePaise: 69900, // ₹699
    currency: 'INR',
    attributes: {
      material: '100% Cotton',
      size: 'L',
      color: 'Off-White',
    },
    stock: 50,
    deliveryInfo: { estimatedDays: 3, shippingFeePaise: 3500, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/fashion/casual-tshirt.png',
  },
  {
    id: 'fashion_002',
    merchantId: 'merchant_aquamart',
    name: 'FlexStride Running Cap',
    category: 'fashion',
    description: 'Lightweight quick-dry performance athletic cap with laser-vented side panels and adjustable metal buckle.',
    pricePaise: 49900, // ₹499
    currency: 'INR',
    attributes: {
      material: 'polyester',
      color: 'Black',
    },
    stock: 35,
    deliveryInfo: { estimatedDays: 2, shippingFeePaise: 3000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/fashion/running-cap.png',
  },
  {
    id: 'fashion_003',
    merchantId: 'merchant_aquamart',
    name: 'SlimLeather Minimal Wallet',
    category: 'fashion',
    description: 'RFID-blocking genuine leather bifold wallet with 6 card slots, bill compartment, and slim front-pocket design.',
    pricePaise: 79900, // ₹799
    currency: 'INR',
    attributes: {
      material: 'genuine_leather',
      color: 'Brown',
    },
    stock: 40,
    deliveryInfo: { estimatedDays: 2, shippingFeePaise: 3500, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/fashion/minimal-wallet.png',
  },
  {
    id: 'fashion_004',
    merchantId: 'merchant_aquamart',
    name: 'ClassicGrip Casual Leather Belt',
    category: 'fashion',
    description: 'Reversible genuine top-grain leather belt with solid zinc alloy pin buckle for formal and casual wear.',
    pricePaise: 59900, // ₹599
    currency: 'INR',
    attributes: {
      material: 'leather',
      color: 'Black/Brown',
    },
    stock: 30,
    deliveryInfo: { estimatedDays: 3, shippingFeePaise: 3500, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/fashion/casual-belt.png',
  },
  {
    id: 'fashion_005',
    merchantId: 'merchant_aquamart',
    name: 'CityPace Everyday Backpack 20L',
    category: 'fashion',
    description: 'Minimalist 20L city backpack with padded 14-inch laptop sleeve, water-resistant canvas fabric, and hidden anti-theft pocket.',
    pricePaise: 179900, // ₹1,799
    currency: 'INR',
    attributes: {
      capacity: '20L',
      material: 'canvas',
      color: 'Charcoal Grey',
    },
    stock: 22,
    deliveryInfo: { estimatedDays: 3, shippingFeePaise: 5000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/fashion/everyday-backpack.png',
  },

  // --- 7. TRAVEL (5) ---
  {
    id: 'travel_001',
    merchantId: 'merchant_aquamart',
    name: 'CommutePro Laptop Travel Backpack 28L',
    category: 'travel',
    description: 'Water-resistant 28L travel backpack featuring dedicated 15.6-inch laptop compartment, luggage trolley strap, and external USB port.',
    pricePaise: 249900, // ₹2,499
    currency: 'INR',
    attributes: {
      capacityLiters: 28,
      laptopSize: '15.6 inch',
      material: 'polyester',
      color: 'Black',
    },
    stock: 29,
    deliveryInfo: { estimatedDays: 2, shippingFeePaise: 5000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/travel/travel-backpack.png',
  },
  {
    id: 'travel_002',
    merchantId: 'merchant_aquamart',
    name: 'PackSmart Packing Cube Set 6-Piece',
    category: 'travel',
    description: '6-piece lightweight mesh travel compression packing cubes set for suitcases with sturdy double zippers and laundry bag.',
    pricePaise: 89900, // ₹899
    currency: 'INR',
    attributes: {
      pieceCount: 6,
      material: 'ripstop_nylon',
      color: 'Grey',
    },
    stock: 38,
    deliveryInfo: { estimatedDays: 2, shippingFeePaise: 4000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/travel/packing-cubes.png',
  },
  {
    id: 'travel_003',
    merchantId: 'merchant_aquamart',
    name: 'Ergofit Travel Memory Foam Neck Pillow',
    category: 'travel',
    description: 'Ergonomic 360-degree memory foam travel neck pillow with breathable washable cover, adjustable rope lock, and eye mask set.',
    pricePaise: 69900, // ₹699
    currency: 'INR',
    attributes: {
      material: 'memory_foam',
      color: 'Dark Blue',
    },
    stock: 42,
    deliveryInfo: { estimatedDays: 3, shippingFeePaise: 3500, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/travel/neck-pillow.png',
  },
  {
    id: 'travel_004',
    merchantId: 'merchant_aquamart',
    name: 'MetroShield Luggage Organizer Set',
    category: 'travel',
    description: 'Waterproof electronics cable organizer travel case with double layer storage pockets for chargers, power banks, and hard drives.',
    pricePaise: 119900, // ₹1,199
    currency: 'INR',
    attributes: {
      material: 'nylon',
      color: 'Black',
    },
    stock: 25,
    deliveryInfo: { estimatedDays: 2, shippingFeePaise: 4000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/travel/luggage-organizer.png',
  },
  {
    id: 'travel_005',
    merchantId: 'merchant_aquamart',
    name: 'GoPouch Hanging Toiletry Travel Pouch',
    category: 'travel',
    description: 'Waterproof hanging toiletry bag with heavy-duty metal swivel hook, transparent mesh compartments, and leakproof lining.',
    pricePaise: 49900, // ₹499
    currency: 'INR',
    attributes: {
      material: 'polyester',
      color: 'Black',
    },
    stock: 50,
    deliveryInfo: { estimatedDays: 2, shippingFeePaise: 3000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/travel/toiletry-pouch.png',
  },

  // --- 8. PERSONAL CARE (5) ---
  {
    id: 'care_001',
    merchantId: 'merchant_aquamart',
    name: 'SonicClean Rechargeable Electric Toothbrush',
    category: 'care',
    description: 'Sonic electric toothbrush delivering 40,000 vibrations per minute, 4 brushing modes, 2-minute smart timer, and 30-day battery life.',
    pricePaise: 169900, // ₹1,699
    currency: 'INR',
    attributes: {
      batteryLife: '30d',
      modes: 4,
      color: 'White',
    },
    stock: 34,
    deliveryInfo: { estimatedDays: 2, shippingFeePaise: 4000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/care/electric-toothbrush.png',
  },
  {
    id: 'care_002',
    merchantId: 'merchant_aquamart',
    name: 'AirFlow Compact Ionic Hair Dryer 1800W',
    category: 'care',
    description: '1800W professional ionic hair dryer with 3 heat settings, cool shot button, foldable handle, and concentrator nozzle.',
    pricePaise: 129900, // ₹1,299
    currency: 'INR',
    attributes: {
      powerWatt: 1800,
      foldable: true,
      color: 'Rose Gold',
    },
    stock: 20,
    deliveryInfo: { estimatedDays: 3, shippingFeePaise: 5000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/care/hair-dryer.png',
  },
  {
    id: 'care_003',
    merchantId: 'merchant_aquamart',
    name: 'PrecisionTrim Waterproof Grooming Trimmer',
    category: 'care',
    description: 'IPX7 waterproof cordless beard and body trimmer with self-sharpening stainless steel blades and 20 length settings (0.5mm-10mm).',
    pricePaise: 149900, // ₹1,499
    currency: 'INR',
    attributes: {
      batteryLife: '90m',
      waterproof: true,
      color: 'Black/Silver',
    },
    stock: 27,
    deliveryInfo: { estimatedDays: 2, shippingFeePaise: 4000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/care/grooming-trimmer.png',
  },
  {
    id: 'care_004',
    merchantId: 'merchant_aquamart',
    name: 'GlowSkin Sonic Face Cleansing Brush',
    category: 'care',
    description: 'Silicone sonic facial cleansing brush with 8 intensity levels, thermal massage head, and magnetic USB charging base.',
    pricePaise: 89900, // ₹899
    currency: 'INR',
    attributes: {
      material: 'silicone',
      waterproof: true,
      color: 'Pink',
    },
    stock: 18,
    deliveryInfo: { estimatedDays: 2, shippingFeePaise: 3500, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/care/cleansing-brush.png',
  },
  {
    id: 'care_005',
    merchantId: 'merchant_aquamart',
    name: 'NeatOrganized Personal Care Cosmetic Organizer',
    category: 'care',
    description: '360-degree rotating acrylic makeup and personal care product organizer with adjustable tray heights.',
    pricePaise: 59900, // ₹599
    currency: 'INR',
    attributes: {
      material: 'acrylic',
      color: 'Clear',
    },
    stock: 0, // OUT OF STOCK TEST ITEM
    deliveryInfo: { estimatedDays: 3, shippingFeePaise: 4000, freeShippingThresholdPaise: 100000, expressAvailable: false },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/care/care-organizer.png',
  },

  // --- 9. OFFICE & STUDY (6) ---
  {
    id: 'office_001',
    merchantId: 'merchant_aquamart',
    name: 'CraftNote A5 Hardcover Dotted Notebook',
    category: 'office',
    description: '192-page A5 hardcover dotted bullet journal with 120gsm bleed-proof paper, inner pocket, and dual ribbon bookmarks.',
    pricePaise: 49900, // ₹499
    currency: 'INR',
    attributes: {
      paperSize: 'A5',
      paperGsm: 120,
      material: 'vegan_leather',
      color: 'Navy Blue',
    },
    stock: 60,
    deliveryInfo: { estimatedDays: 2, shippingFeePaise: 3000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/office/hardcover-notebook.png',
  },
  {
    id: 'office_002',
    merchantId: 'merchant_aquamart',
    name: 'Ergofit Aluminum Ergonomic Laptop Stand',
    category: 'office',
    description: 'Ventilated foldable aluminum laptop stand supporting up to 17-inch laptops with 6 ergonomic height adjustments.',
    pricePaise: 99900, // ₹999
    currency: 'INR',
    attributes: {
      material: 'aluminum',
      color: 'Silver',
      maxWeightKg: 10,
    },
    stock: 38,
    deliveryInfo: { estimatedDays: 2, shippingFeePaise: 4000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/office/laptop-stand.png',
  },
  {
    id: 'office_003',
    merchantId: 'merchant_aquamart',
    name: 'ClearSpace Mesh 4-Tier Desk Organizer',
    category: 'office',
    description: 'Sturdy steel mesh desk organizer with sliding drawer, letter tray, double pen holders, and file sorter rack.',
    pricePaise: 69900, // ₹699
    currency: 'INR',
    attributes: {
      material: 'steel_mesh',
      tiers: 4,
      color: 'Black',
    },
    stock: 45,
    deliveryInfo: { estimatedDays: 2, shippingFeePaise: 4000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/office/desk-organizer.png',
  },
  {
    id: 'office_004',
    merchantId: 'merchant_aquamart',
    name: 'PrecisionWrite Gel Pen Set 5-Pack',
    category: 'office',
    description: '0.5mm quick-dry Japanese black gel ink pens set with rubber grip barrel for smooth writing without smudging.',
    pricePaise: 39900, // ₹399
    currency: 'INR',
    attributes: {
      tipSize: '0.5mm',
      inkColor: 'Black',
      quantity: 5,
    },
    stock: 70,
    deliveryInfo: { estimatedDays: 2, shippingFeePaise: 2500, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/office/gel-pen-set.png',
  },
  {
    id: 'office_005',
    merchantId: 'merchant_aquamart',
    name: 'LuminaFlex LED Dimmable Study Lamp',
    category: 'office',
    description: 'Eye-caring LED desk lamp with 5 color temperatures, touch controls, USB output port, and flexible gooseneck arm.',
    pricePaise: 129900, // ₹1,299
    currency: 'INR',
    attributes: {
      powerSource: 'USB',
      colorTemps: 5,
      color: 'White',
    },
    stock: 25,
    deliveryInfo: { estimatedDays: 3, shippingFeePaise: 4500, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/office/study-lamp.png',
  },
  {
    id: 'office_006',
    merchantId: 'merchant_aquamart',
    name: 'FlexiFolder Expanding Document Organizer',
    category: 'office',
    description: '12-pocket expanding A4 accordian file organizer folder with tab labels and secure elastic closure cord.',
    pricePaise: 29900, // ₹299
    currency: 'INR',
    attributes: {
      paperSize: 'A4',
      pockets: 12,
      color: 'Black',
    },
    stock: 80,
    deliveryInfo: { estimatedDays: 2, shippingFeePaise: 2500, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns.',
    active: true,
    imageUrl: '/products/office/document-folder.png',
  },

  // --- 10. LIFESTYLE (6) ---
  // Canonical Match 1 (1L, stainless steel, under ₹2,000, in stock)
  {
    id: 'bottle_001',
    merchantId: 'merchant_aquamart',
    name: 'HydroPro 1L Stainless Steel Water Bottle',
    category: 'lifestyle',
    description: 'Double-wall vacuum insulated 1L stainless steel water bottle. Keeps drinks cold for 24h and hot for 12h. Perfect for travel.',
    pricePaise: 169900, // ₹1,699
    currency: 'INR',
    attributes: {
      capacity: '1L',
      material: 'stainless_steel',
      insulation: true,
      color: 'Silver',
      weightGrams: 420,
    },
    stock: 23,
    deliveryInfo: { estimatedDays: 3, shippingFeePaise: 5000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days easy returns and replacement guarantee.',
    active: true,
    imageUrl: '/products/lifestyle/bottle_001.png',
  },
  // Canonical Match 2 (1L, stainless steel, under ₹2,000, in stock)
  {
    id: 'bottle_002',
    merchantId: 'merchant_aquamart',
    name: 'EcoSteel 1L Insulated Flask',
    category: 'lifestyle',
    description: 'Ergonomic 1L premium stainless steel hydration bottle with powder-coat anti-slip finish. Travel friendly carrying loop.',
    pricePaise: 149900, // ₹1,499
    currency: 'INR',
    attributes: {
      capacity: '1L',
      material: 'stainless_steel',
      insulation: true,
      color: 'Matte Black',
      weightGrams: 390,
    },
    stock: 15,
    deliveryInfo: { estimatedDays: 2, shippingFeePaise: 5000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days returns.',
    active: true,
    imageUrl: '/products/lifestyle/bottle_002.png',
  },
  // Canonical Match 3 (1L, stainless steel, under ₹2,000, in stock)
  {
    id: 'bottle_003',
    merchantId: 'merchant_aquamart',
    name: 'TerraVessel 1L Stainless Flask',
    category: 'lifestyle',
    description: 'Single-wall lightweight 1 litre stainless steel sports bottle. Durable, BPA-free leakproof cap ideal for outdoor adventures.',
    pricePaise: 189900, // ₹1,899
    currency: 'INR',
    attributes: {
      capacity: '1L',
      material: 'stainless_steel',
      insulation: false,
      color: 'Navy Blue',
      weightGrams: 280,
    },
    stock: 10,
    deliveryInfo: { estimatedDays: 4, shippingFeePaise: 0, freeShippingThresholdPaise: 100000, expressAvailable: false },
    returnPolicy: '15 days return policy.',
    active: true,
    imageUrl: '/products/lifestyle/bottle_003.png',
  },
  // Above ₹2,000 test case (1L, stainless steel, ₹2,499)
  {
    id: 'bottle_004',
    merchantId: 'merchant_aquamart',
    name: 'TitanThermo 1L Ultra Vacuum Flask',
    category: 'lifestyle',
    description: 'Heavy-duty 1L pro titanium-coated stainless steel flask with temperature display lid and internal strainer.',
    pricePaise: 249900, // ₹2,499 (> ₹2,000 limit)
    currency: 'INR',
    attributes: {
      capacity: '1L',
      material: 'stainless_steel',
      insulation: true,
      color: 'Titanium Grey',
      weightGrams: 510,
    },
    stock: 8,
    deliveryInfo: { estimatedDays: 2, shippingFeePaise: 0, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days returns.',
    active: true,
    imageUrl: '/products/lifestyle/bottle_004.png',
  },
  // Out of stock test case
  {
    id: 'bottle_005',
    merchantId: 'merchant_aquamart',
    name: 'PureFlow 1L Steel Hydrator',
    category: 'lifestyle',
    description: 'Sleek 1L stainless steel water bottle in rose gold finish. Ultra durable copper lining.',
    pricePaise: 129900, // ₹1,299
    currency: 'INR',
    attributes: {
      capacity: '1L',
      material: 'stainless_steel',
      insulation: true,
      color: 'Rose Gold',
      weightGrams: 370,
    },
    stock: 0, // Out of stock (stock = 0)
    deliveryInfo: { estimatedDays: 5, shippingFeePaise: 5000, freeShippingThresholdPaise: 100000, expressAvailable: false },
    returnPolicy: '30 days returns.',
    active: true,
    imageUrl: '/products/lifestyle/bottle_005.png',
  },
  {
    id: 'bottle_006',
    merchantId: 'merchant_aquamart',
    name: 'ActiveGrip 750ml Sport Bottle',
    category: 'lifestyle',
    description: 'Compact 750ml stainless steel bottle designed for gym holders and bicycle bottle cages.',
    pricePaise: 99900, // ₹999
    currency: 'INR',
    attributes: {
      capacity: '750ml',
      material: 'stainless_steel',
      insulation: true,
      color: 'Electric Blue',
      weightGrams: 310,
    },
    stock: 40,
    deliveryInfo: { estimatedDays: 3, shippingFeePaise: 4000, freeShippingThresholdPaise: 100000, expressAvailable: true },
    returnPolicy: '30 days returns.',
    active: true,
    imageUrl: '/products/lifestyle/bottle_006.png',
  },
];
